"""added distance_from_start column to route_stop

Revision ID: 14794913594d
Revises: b666e6a349ef
Create Date: 2026-06-13 10:41:52.594858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14794913594d'
down_revision: Union[str, Sequence[str], None] = 'b666e6a349ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routestop', sa.Column('distance_from_start', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routestop', 'distance_from_start')
    # ### end Alembic commands ###
