"""added new column active to schedule

Revision ID: 2bae61ff1cc1
Revises: 950b04812047
Create Date: 2026-06-27 17:22:22.675215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bae61ff1cc1'
down_revision: Union[str, Sequence[str], None] = '950b04812047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'active')
    # ### end Alembic commands ###
