"""added new columns to tickets

Revision ID: 30237da7a33a
Revises: f104606b82a4
Create Date: 2026-06-19 10:43:09.452864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30237da7a33a'
down_revision: Union[str, Sequence[str], None] = 'f104606b82a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('fare', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('mode_of_transaction', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'mode_of_transaction')
    op.drop_column('tickets', 'fare')
    op.drop_column('tickets', 'user_id')
    # ### end Alembic commands ###
