"""added distance column to ticket

Revision ID: 4fca73a733f5
Revises: 14794913594d
Create Date: 2026-06-13 11:00:54.380820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fca73a733f5'
down_revision: Union[str, Sequence[str], None] = '14794913594d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'distance')
    # ### end Alembic commands ###
