"""added new columns to tickets

Revision ID: 950b04812047
Revises: 30237da7a33a
Create Date: 2026-06-27 12:29:22.939945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950b04812047'
down_revision: Union[str, Sequence[str], None] = '30237da7a33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('reverse', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'reverse')
    op.drop_column('schedules', 'end_time')
    op.drop_column('schedules', 'start_time')
    # ### end Alembic commands ###
