"""added start and end stop to tickets

Revision ID: b666e6a349ef
Revises: ce6fcc1c4831
Create Date: 2026-06-12 10:51:49.506121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b666e6a349ef'
down_revision: Union[str, Sequence[str], None] = 'ce6fcc1c4831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('start_stop_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('end_stop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'stops', ['end_stop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'stops', ['start_stop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'end_stop_id')
    op.drop_column('tickets', 'start_stop_id')
    # ### end Alembic commands ###
